library(jiebaR)
library(stringr)
library(dplyr)
library(wordcloud2)
data <- read.csv("C:\\Users\\WeiEnsong\\Desktop\\data.csv",encoding="utf-8")
data <- unique(data)
text <- gsub('[a-zA-Z0-9]','',data$news_content)
wk <- worker()
words <- segment(text,wk)
text_df <-tibble(line = c(1:length(words)),word = words)
count(text_df,word,sort = T)
text_df <- text_df %>% count(word,sort =TRUE)
wordcloud2(text_df, size=1)
wordcloud2(text_df)
